########################################################
# HEIMDALL HOMEPAGE
########################################################

services:
    heimdall:
        container_name: heimdall
        image: lscr.io/linuxserver/heimdall:latest@sha256:d992875cb63c643ed5c8c450fb96f0ed112444c349a4845e043c2341142e17db
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/heimdall:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.heimdall-rtr.rule: Host(`${HEIMDALL_DOMAIN:-heimdall}.${DOMAIN_NAME}`)
            traefik.http.routers.heimdall-rtr.entrypoints: web
            traefik.http.routers.heimdall-rtr.service: heimdall-svc
            traefik.http.services.heimdall-svc.loadbalancer.server.port: 80
            traefik.http.routers.heimdall-rtr.middlewares: chain-rate-limit@file
