#######################################
# OVERSEERR (DOWNLOAD REQUESTS)
#######################################

services:
    overseerr:
        container_name: overseerr
        image: lscr.io/linuxserver/overseerr:latest@sha256:feddc11664639721d4e220d161ce5eb8fd2483d2e252e3e119570abcce3c7474
        profiles: ["media", "all"]
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/overseerr:/config
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.overseerr-rtr.rule: Host(`${OVERSEERR_SUBDOMAIN:-overseerr}.${DOMAIN_NAME}`)
            traefik.http.routers.overseerr-rtr.entrypoints: websecure
            traefik.http.routers.overseerr-rtr.service: overseerr-svc
            traefik.http.services.overseerr-svc.loadbalancer.server.port: 5055
            traefik.http.routers.overseerr-rtr.middlewares: chain-oauth-google@file
