#######################################
# PLEX (MOVIES AND TV SERVER)
#######################################

services:
    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex:latest@sha256:ab81c7313fb5dc4d1f9562e5bbd5e5877a8a3c5ca6b9f9fff3437b5096a2b123
        profiles: ["media", "all"]
        network_mode: host
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/plex:/config
            - ${TV_DIR}:/tv
            - ${MOVIE_DIR}:/movies
            - ${TRANSCODE_DIR:-/dev/shm}:/transcode
            - ${BOOKS_DIR}:/books
        devices:
            - /dev/dri:/dev/dri
            - /dev/dvb:/dev/dvb
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            VERSION: docker
            PLEX_CLAIM: ${PLEX_CLAIM}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
