# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# POSTGRESQL (DATABASE)
#######################################

services:
    homelab-postgres:
        container_name: homelab-postgres
        image: postgres:18.1@sha256:38d5c9d522037d8bf0864c9068e4df2f8a60127c6489ab06f98fdeda535560f9
        profiles: ["utilities", "all"]
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES:-}
        networks:
            internal:
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/homelab-postgres:/var/lib/postgresql/data
            - ${DOCKER_DIRECTORY}/scripts/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
        restart: always
        healthcheck:
            test:
                [
                    CMD-SHELL,
                    "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
